name: new_project

packages:
  - .
  - example
  - apps/*
  - packages/*
  - packages/*/example

scripts:
  worker2js: melos worker2jsImageMerge
  worker2jsImageMerge:
    exec: cd web && dart compile js imageMergeTransform.dart -o imageMergeTransform.js -O4
    packageFilters:
      scope: 'example'

  outdated:
    exec: dart pub outdated
  upgrade:
    exec: dart pub upgrade
  gen:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
  analyze:
    exec: dart analyze .
  fix:
    exec: dart fix --apply
  format:
    exec: dart format .
  sort:
    exec: dart pub global run import_sorter:main --no-comments
  precommit: melos fix && melos format && melos sort
  test:
    run: flutter test --no-pub --coverage
    exec:
      concurrency: 1
    packageFilters:
      dirExists: test
